// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rptvryllbkebheqfajwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwdHZyeWxsYmtlYmhlcWZhandlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTgyMTMsImV4cCI6MjA2OTQ3NDIxM30.kVuq0w2c_tNUjbPOOxw8LdqBXvKdjbXskkPLZCvTNOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);