// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogzoaossnynysepsiuxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nem9hb3NzbnlueXNlcHNpdXh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NzIzNDcsImV4cCI6MjA2NTA0ODM0N30.0QEe69U76A6iRGUvzC1qQhfzmHZFp9oBsSGDXdRzR44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);